### ISSUE TITLE
Using config file: `Error: failed to read config`

### ISSUE THREAD

**Issue by Fluhzar** [lhvy/pipes-rs#125]
When running pipes-rs with settings set in a config file at `~/.config/pipes-rs/config.toml`, omitting the `license` field causes a parser error.

With a config like:
```toml
color_mode = "rgb"
delay_ms = 42
inherit_style = true
kinds = ["heavy"]
num_pipes = 16
palette = "default"
reset_threshold = 0.0
turn_chance = 0.1
```

Running
```
$ pipes-rs
```
yields:

```
Error: failed to read config

Caused by:
    TOML parse error at line 1, column 1
      |
    1 | color_mode = "rgb"
      | ^^^^^^^^^^^^^^^^^^
    missing field `license`
```

Even an empty config file will yield this error.

Adding `license = false` resolves the issue, but seems a little silly to have that field be required in the first place.
